services:
  web:
    build: server
    ports:
      - "8000:8000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:8000/flask-health-check || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 120 -b 0.0.0.0:8000 app:app
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      web:
        condition: service_healthy
    command:
      - "http"
      - "8000"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
